const Chart = () => {
    return ( 
        <div className="chart">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus impedit quas esse tenetur mollitia omnis qui facilis officia minima rem? Inventore impedit eligendi placeat alias, omnis perspiciatis minima dolorem maiores.
            Culpa neque ut quam sunt quasi enim id fuga, ea omnis laudantium! Cupiditate quasi molestiae repellat voluptates. Repellendus ab pariatur excepturi, reiciendis maxime culpa illo dolorum debitis vitae labore sit?
            Soluta repellat distinctio voluptas ea? Ab doloribus, nihil molestiae vitae ea asperiores eaque deleniti non aut corrupti sint quaerat tenetur tempora sequi tempore cumque sunt, sed ullam voluptas esse ad.
            Voluptas tempore quod eveniet reprehenderit ea animi incidunt, porro illum facilis iusto non nisi saepe suscipit nam, laudantium amet omnis unde officia nihil ipsam error earum deserunt! Tempora, nulla dicta.
            Numquam, at voluptates. Ab illum nobis distinctio ad tenetur, quidem modi eos veritatis laudantium minima magnam! Voluptate, dolorem corrupti dolor sequi ullam voluptates illum impedit vero commodi? Ut, numquam minima?
            Quam laudantium animi, sapiente hic sint reiciendis odio delectus amet cupiditate. Repellat enim iusto quasi, ab beatae, laborum placeat qui fuga harum saepe quibusdam dolores unde, autem cumque ad doloremque!
            Repudiandae modi distinctio dolores dignissimos illo quaerat maxime, ut omnis ullam nam, quibusdam excepturi doloremque ex officiis repellat non inventore a sunt dolorem iure vero ratione consequatur asperiores. Harum, modi!
            Architecto a sit quaerat corrupti minus delectus! Eligendi quos necessitatibus inventore doloribus! Eius nam quae beatae iure harum, incidunt, libero deserunt quisquam tempore dolorem laborum molestiae sunt qui vero reiciendis.
            Doloribus inventore expedita quaerat similique libero incidunt delectus tempore. Consectetur, non dicta. Laboriosam natus ipsa itaque laborum numquam eaque? Dolor labore pariatur ducimus aliquid obcaecati tempore distinctio ratione consequuntur maiores!
            Fuga dolore, nihil ea, molestiae quod earum deleniti repudiandae totam distinctio quas ratione sunt accusamus molestias labore repellendus maxime esse asperiores magnam maiores eos perspiciatis cupiditate aspernatur aut sapiente. Officia!
            Debitis saepe aperiam laudantium provident obcaecati aliquam officiis natus asperiores? Distinctio amet corrupti reprehenderit minima at natus fugiat repellat tenetur saepe quas quisquam incidunt, blanditiis nam error modi laudantium sit!
            Perferendis incidunt in sed aperiam quod aut, eveniet aliquam numquam iste sequi suscipit necessitatibus minus molestiae ab. Eum, enim adipisci? Consequuntur dolore animi delectus odio minus minima explicabo id corrupti.
            Adipisci perferendis dignissimos repellendus modi illo iusto quo, rem minima quasi, similique, consectetur corrupti officia fugit cum eveniet dolorum excepturi quas maxime soluta? Dignissimos non quod optio amet deleniti? Non?
            Impedit pariatur eaque illum. Libero, incidunt molestias eligendi, perspiciatis consequatur itaque a autem vero non sed, consectetur magni vel reprehenderit ullam vitae beatae hic recusandae minus? Optio iure magni maxime?
            Libero sunt facilis laudantium iste. Quos officia ea alias totam quas, cupiditate quasi, ratione perspiciatis, impedit sit magni aliquam atque quisquam iusto fugiat sunt ullam consequuntur vitae est ut quia!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus aliquam tenetur sunt culpa magni libero! Eaque voluptatem assumenda voluptatibus molestias labore nam porro necessitatibus, voluptas id reiciendis. Fuga, quam qui?
            Tempora ex possimus pariatur beatae dolorem blanditiis libero vel debitis earum praesentium, voluptates inventore explicabo velit! Expedita minima placeat nostrum deserunt libero dolor maiores in magni. Nostrum ipsa iusto officiis.
            Eos nostrum similique qui unde, autem facilis atque iure velit sint assumenda. Sint architecto perferendis laborum similique cupiditate asperiores adipisci, debitis enim! Voluptas ut velit sit alias hic sunt a.
            Itaque pariatur commodi doloremque, quos hic aliquid fugit explicabo optio qui illum corrupti eveniet ipsum dolorem, fuga repudiandae quae, accusamus ullam repellat? Provident optio rerum nisi animi repellendus ad non.
            Dicta id illo rerum nihil error quos rem totam odit quod corporis voluptates alias veritatis maxime fugiat blanditiis atque natus, eveniet necessitatibus quis earum nam facere porro accusamus. Voluptatem, blanditiis?
            Illum asperiores, aspernatur fuga veritatis vel eius illo quae beatae dolorum porro voluptas repellendus nesciunt recusandae voluptate quis reiciendis explicabo iste aut odit quas officia? Quod ex pariatur inventore! Ipsam?
            Blanditiis necessitatibus, eos perferendis architecto consectetur nulla, voluptate impedit similique sunt corporis quos ipsam distinctio hic autem temporibus ipsa. Sint deserunt, cupiditate quasi ullam molestias maxime voluptatibus ad accusantium tenetur.
            Culpa eveniet ipsa, asperiores esse doloremque perferendis assumenda id odit, temporibus distinctio dignissimos commodi minima quo rerum tempora nulla ipsam consequuntur voluptatibus. Dolor magnam porro deleniti atque harum esse nulla.
            Ut, a soluta iste aperiam vitae voluptatem! Nostrum nobis dignissimos autem perferendis a possimus dolorem atque facere in vero id excepturi laudantium voluptas quo itaque eum, provident, et, animi repellat.
            Est quas quo, ratione suscipit quia dolores itaque doloremque sed molestias, temporibus nisi soluta hic porro dolore. Rerum nobis impedit quidem illo quas repudiandae placeat id ea? Optio, fuga accusantium.
            Ipsum voluptatum quisquam sunt maiores voluptas quam illo voluptates quibusdam! Sunt, magni assumenda? Aspernatur modi id amet, excepturi ullam dolorum in quia sapiente, nesciunt cupiditate aliquid voluptatibus expedita possimus quisquam?
            Eligendi cupiditate doloremque esse unde non veniam aperiam vero alias reprehenderit! Aliquam eligendi explicabo tempore, perspiciatis error laudantium voluptates excepturi consectetur sunt, nisi nobis dolores quasi optio molestiae, maxime odio!
            Placeat harum velit voluptatum doloremque tenetur, hic, exercitationem pariatur quas quos eaque culpa sunt quae vel nihil expedita animi possimus quod, quam praesentium deleniti ullam alias corrupti similique! Pariatur, ipsam!
            Laborum est consequuntur adipisci illum voluptatum odit et natus fugit iusto! Quas, labore. Voluptate nostrum ipsum tempora nulla vel. Saepe aspernatur modi, vel iusto incidunt nostrum quod illum! Molestias, eius.
            Eaque qui numquam, quas ipsa soluta voluptates, hic exercitationem illum impedit minima nihil perferendis reiciendis provident maxime quidem eius ipsum nemo quo tenetur adipisci quasi ab voluptas! Eum, consequuntur expedita.
            Odit, ad? Nesciunt, dolorem officia dolores laboriosam porro quam similique suscipit nobis sunt. Ratione repellendus consequatur aspernatur architecto vitae voluptas, laborum sed tenetur alias beatae, vel quaerat quisquam laudantium doloribus.
            Magnam molestiae et nemo odit quam doloribus iste tempora illum magni veritatis nam, assumenda rem omnis animi! Tenetur necessitatibus dignissimos error eum voluptatibus qui quidem consectetur voluptas vel, repellendus voluptate.
            Ducimus quisquam commodi aliquam expedita sit! Minus reprehenderit molestiae esse, voluptatem hic facere nobis debitis repudiandae, delectus consequatur cum sapiente cupiditate quaerat assumenda possimus fuga corporis consectetur. Iste, veniam eligendi?
            Modi totam ducimus adipisci architecto vitae. Fuga tempore ducimus aspernatur ratione dicta amet aliquam sequi! Inventore ut commodi, iure eaque ipsam officiis perspiciatis iste quod non maiores laudantium cum! Dolorem?
            Ut deleniti sit odio, rem et modi tenetur facere eius distinctio deserunt porro, saepe dolores natus nam ullam consectetur enim temporibus quae dolorum voluptatum nulla voluptates iusto. Quibusdam, quidem perferendis.
            Voluptatum laudantium repudiandae aliquid, eligendi iste ab quae ratione iure blanditiis ex totam minima beatae voluptatibus saepe mollitia deleniti quisquam laboriosam, soluta in. Ea veritatis accusamus, eum rem quia optio!
            Neque nulla necessitatibus esse eligendi fuga nam facilis corporis quod dolor voluptate, officia distinctio atque magnam. Qui minima, iusto nisi beatae ex, laboriosam dolorum inventore, illo quis optio sint nam.
            Voluptatibus hic et eum, quo aliquam porro ab fugit corrupti! Itaque fugiat perspiciatis, quam, sit illo quas neque molestiae, error cum aliquid iusto rem magnam! Nobis deserunt sunt ipsa esse!
            Sunt cum nostrum earum quod dolore enim reprehenderit maiores repudiandae perspiciatis debitis quo facere quos consequatur accusantium, numquam eligendi. Delectus rem ipsa quia in consequuntur optio, praesentium quidem exercitationem consequatur.
            Dolor illum est nostrum! Obcaecati quos accusamus facilis maiores at. Blanditiis ipsa deserunt, quisquam voluptas modi explicabo! Quasi harum exercitationem neque nam inventore unde possimus fugiat molestiae non. Alias, ullam.
            Ipsum nisi iusto id numquam vel reiciendis fugiat facilis, similique itaque repudiandae repellat reprehenderit consectetur illum animi! Voluptatum totam, tenetur tempora dolores nam quas ullam, illum consectetur ut eveniet esse?
            Earum saepe cumque sapiente voluptatem deleniti blanditiis cupiditate ratione maxime animi iste eius tempora debitis nam distinctio quibusdam reiciendis, commodi, laudantium hic perspiciatis error ex soluta laboriosam assumenda rem. Laboriosam!
            Error impedit explicabo quia, mollitia ad facere ullam animi veritatis sequi amet corrupti beatae saepe ipsa facilis aut ipsum. Natus, tempore. Dolorem quisquam totam fuga fugiat atque laboriosam rerum provident.
            Voluptas corrupti aut sunt repellat est magni nihil eum dolor veniam, magnam modi officia saepe numquam incidunt deleniti quia fugiat iure accusamus ex quasi neque! Suscipit, atque. Quas, praesentium itaque!
            Quam excepturi cupiditate culpa quos modi nihil impedit distinctio sed hic vel, in magni sint, laborum veritatis amet. Ipsam, porro quos? Vel facilis veniam veritatis, odit minus dolorum illum reprehenderit.
            Eius veniam, deleniti maiores optio laboriosam assumenda, consequatur fuga necessitatibus nesciunt a distinctio minima praesentium, eligendi aliquid? Eos ex perspiciatis voluptate cum omnis neque? Delectus corrupti ducimus odio eaque saepe.
            Maxime suscipit ipsam corrupti porro tempore doloribus accusantium eaque necessitatibus qui deserunt, aspernatur explicabo nisi odio minus rem nemo quae provident, totam ipsum perferendis exercitationem voluptate a! Quas, beatae necessitatibus.
            Quis odit, voluptate quo quisquam voluptas dicta soluta quasi nostrum temporibus laudantium dolor aut fugit deleniti recusandae enim tempora quaerat, velit excepturi. Harum, nemo modi doloribus laboriosam ad vitae possimus.
            Rerum modi facilis, libero praesentium laudantium nam nesciunt. Corporis facere repellendus ipsa suscipit repellat ullam molestias nesciunt doloribus et velit, nisi asperiores hic qui deserunt, aliquam quaerat ipsum nobis odio!
            Explicabo voluptatibus alias et quidem quo quisquam aliquam cupiditate recusandae laborum autem animi vero, eius eaque distinctio? Optio, obcaecati, in facere mollitia, reiciendis similique quam fugiat alias minus voluptas voluptatum.
            Ut vitae distinctio fugit in animi id voluptatibus libero, sunt optio omnis porro voluptatem quam, dignissimos iusto perspiciatis assumenda quod. Maxime atque veritatis voluptatibus, impedit reprehenderit iste asperiores nam autem.
            Molestiae eos sint voluptatem rerum cupiditate? Quo animi ipsa perspiciatis officiis. Dolorem, consequatur sapiente error aliquid officia, hic possimus cum ducimus odit quasi voluptate natus. Dolore repellat debitis eligendi quibusdam.
            Debitis voluptatem sint ad vel et incidunt nam deleniti consectetur illum, repellendus, cumque ratione laudantium dolore architecto quisquam cupiditate! Laudantium voluptate praesentium aliquam, consectetur blanditiis ex harum impedit enim eligendi.
            Ad culpa repellendus atque fuga totam quas quisquam nihil, modi, cupiditate non debitis et a quo error hic nobis corporis adipisci rerum, quasi libero commodi doloribus voluptatem pariatur. Impedit, amet.
            Facere quibusdam at alias unde eaque sit sequi aliquam nulla similique? Consequatur accusamus omnis doloremque in hic culpa ipsa, debitis temporibus quo dolorum, earum natus cumque illo quod esse tenetur.
            Voluptates ut, accusamus nobis consectetur doloremque dicta minus quam consequatur quia eaque! Architecto vel sint recusandae odit rerum sed atque voluptatem, quisquam nesciunt ut tempora eveniet dolorum dolores dolorem quis?
            Aut suscipit tempora sit accusantium officiis, ipsum vero sint voluptatum ab dolorum nesciunt, quidem quibusdam consequuntur possimus amet qui natus quasi quisquam aperiam autem pariatur. Magni non perspiciatis maxime corporis!
            Quos eligendi libero tempore aliquam? Ipsa nihil quia distinctio architecto quaerat optio, est adipisci! Nam, impedit facere possimus quam hic totam blanditiis laborum obcaecati at modi neque, unde inventore laboriosam?
            Magnam quibusdam porro libero sapiente dicta voluptas nemo laudantium ducimus pariatur odio autem ab architecto odit, illum, corrupti iusto! Magni accusantium vitae corrupti? Consectetur ipsa distinctio temporibus tempora, quibusdam atque!
            Iste officia reiciendis, neque praesentium sit illo nihil blanditiis aliquam sint voluptatibus architecto quis nulla quae? Animi laboriosam provident culpa recusandae dicta necessitatibus placeat, dolores ab. Atque ducimus magnam fugiat!
            Asperiores iste doloremque porro quia? Itaque porro, atque neque iste hic error similique possimus consequuntur animi eveniet, quidem consectetur quo veniam pariatur ipsa modi ullam est corporis id ex deleniti!
            Accusamus, qui! Adipisci, aliquam accusamus iure consectetur nulla excepturi, aperiam sapiente laudantium cupiditate tempora fuga praesentium ut modi quisquam itaque qui est nemo architecto impedit corporis autem eius eum voluptate.
            Illo rerum repudiandae ea nulla dolor obcaecati sint officiis, nisi accusantium odio, voluptate adipisci magni suscipit! Quia dolorum magnam omnis cupiditate error facere. Laborum facilis tenetur deserunt beatae consequuntur cupiditate.
            Enim, nulla quam pariatur esse ab odio illo iste corrupti veritatis maxime optio ipsam totam fugiat quaerat accusamus laboriosam labore, officiis sapiente quia eos modi quibusdam. Aliquid aperiam quia delectus?
            Suscipit libero cupiditate veniam maxime dolor veritatis impedit excepturi architecto facilis voluptatem dolorem, quod sed iusto eveniet natus ex, earum provident facere nobis laboriosam. Aspernatur itaque harum natus tenetur beatae.
        </div>
     );
}
 
export default Chart;